# Basis-Image für HTML, CSS und JavaScript
FROM nginx:latest

# Arbeitsverzeichnis für die Anwendung
WORKDIR /usr/share/nginx/html

# Code in das Arbeitsverzeichnis kopieren
COPY . /usr/share/nginx/html

# Port 80 freigeben und server starten
EXPOSE 80
