version: "3.8"
services:
  backend:
    build: ./backend
    # image: backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb+srv://goerresvalerenintidemkemlikeu:CGxLhbHBNtqADug3@cluster.27xqb.mongodb.net/

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongo_data:
